### ISSUE TITLE
Default network protocols

### ISSUE THREAD

**Issue by Mikerah** [ConsenSys/wittgenstein#34]
Hi,

I am planning on writing a Dandelion++ Simulation on top of a gossipsub network in order to test some ideas outlined in this [issue](https://github.com/ethresearch/p2p/issues/11).

As it currently stands, I would have to build 2-3 protocols, one for a gossipsub network, one for Dandelion++ and another for sharding. 

As a potential future feature of this simulation library, would it make sense to have some default network protocols  that simulators can choose from?

**Comment by nkeywal** [comment]
Hi Mikerah,

It's worth trying. The risk is to over-engineering it: a gossip protocol can be hacked in 1 hour, but you can also spend a year on it.  In a simulator you prefer to stay closer to the 1 hour side ;-). But definitively it's worth trying.
