### ISSUE TITLE
POW Sim

### ISSUE THREAD

**Issue by vanessabridge** [ConsenSys/wittgenstein#59]
Build a protocol that simulates pow algorithms, uses difficulty calculations and includes uncles:

For Uncle creation
**Before adding as uncle:**
- [x] Validate that block received has the same parent as existing block at same height 
- [x] Check block by height in blockchain  and add as uncle if same parent and hasn’t been included and there are less than 2 uncles at that height
- [x] Prevent uncles past height+6 to be added

**Refactoring**
- [x] Remove uncle reference from the node

**Mining**
- [x] Adjust difficulty calculation to include uncles
- [x] Validate calculations using real data from main net in a test
- [x]  Create reward functions that allocates funds for successfully mining: 1) block + transaction fees 2) an uncle

** Data collection**
- [ ]  Generate stats for uncles and record them in a separate file (csv)
- [ ] Select minimal parameters necessary to feed to RL agent
- [ ] Set method that calls agent at decision points

Generate data and store it outside with minimum parameters necessary

**Comment by vanessabridge** [comment]
#58

**Comment by nkeywal** [comment]
Merged.
